//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusMVCCrudOperation.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BusTracking
    {
        public int BusID { get; set; }
        [Required (ErrorMessage ="Enter the BoardingPoint ")]
        public string BoardingPoint { get; set; }
        [Required (ErrorMessage ="Enter the TravelDate")]
        public Nullable<System.DateTime> TravelDate { get; set; }
        [Required (ErrorMessage = "Amount")]
        public Nullable<decimal> Amount { get; set; }
        [Required (ErrorMessage = "Enter Rating")]
        public Nullable<int> Rating { get; set; }
    }
}
